spring:
  profiles:
    active: dev


--
server:
  port: 8021

spring:
  profiles: dev
  application:
    name: cloud-config-client
eureka:
  client:
    service-url:
      #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址
      defaultZone: http://eureka7001.com:7001/eureka/

  --
server:
  port: 8022

spring:
  profiles: test
  application:
    name: cloud-config-client
eureka:
  client:
    service-url:
      #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址
      defaultZone: http://eureka7001.com:7001/eureka/