spring:
  profiles:
    active: dev


---
server:
  port: 8021

spring:
  profiles: dev
  application:
    name: cloud-config-client


---
server:
  port: 8022

spring:
  profiles: test
  application:
    name: cloud-config-client
